language: android

sudo: true

android:
  components:
  - platform-tools
  - android-23
  - tools
  - build-tools-23.0.3
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services

notifications:
  email: false

before_install:
  - chmod +x gradlew

jdk:
- oraclejdk8
 
script: 
  - ./gradlew assembleDebug
